package com.example.dicket.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a category entity in the Dicket application.
 *
 * @property categoryID Unique identifier for the category (auto-generated by Room).
 * @property name The name of the category.
 */
@Entity(tableName = "Category")
data class Category(
    @PrimaryKey(autoGenerate = true)
    var categoryID: Int,
    var name: String
)
