package com.example.dicket.data.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import java.time.LocalDate
import java.time.LocalTime

/**
 * Represents an event entity in the Dicket application.
 *
 * @property eventID Unique identifier for the event (auto-generated by Room).
 * @property title The title of the event.
 * @property rating The rating of the event.
 * @property description The description of the event.
 * @property minAge The minimum age required for attendees.
 * @property entry The entry time of the event.
 * @property date The date of the event.
 * @property location The ID of the associated location (foreign key).
 * @property image The image URL or path associated with the event.
 * @property category The ID of the associated category (foreign key).
 * @property price The price of the event.
 * @property latestCancelingDate The timestamp for the latest canceling date.
 * @property maxQuantityTicket The maximum quantity of tickets available for the event.
 * @property organizer The ID of the event organizer (foreign key).
 */
@Entity(
    tableName = "Event",
    foreignKeys = [
        ForeignKey(
            entity = Location::class,
            parentColumns = ["locationID"],
            childColumns = ["location"]
        ),
        ForeignKey(
            entity = Category::class,
            parentColumns = ["categoryID"],
            childColumns = ["category"]
        ),
        ForeignKey(
            entity = User::class,
            parentColumns = ["userID"],
            childColumns = ["organizer"]
        )
    ]
)
data class Event(
    @PrimaryKey(autoGenerate = true)
    val eventID: Int,
    var title: String,
    var rating: Float,
    var description: String,
    var minAge: Int,
    var entry: LocalTime,
    var date: LocalDate,
    var location: Int,
    var image: String,
    var category: Int,
    var price: Double,
    var latestCancelingDate: Long,
    var maxQuantityTicket: Int,
    var organizer: Int
)
