package com.example.dicket.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a user entity in the Dicket application.
 *
 * @property userID Unique identifier for the user (auto-generated by Room).
 * @property prename The user's first name.
 * @property surname The user's last name.
 * @property email The user's email address.
 * @property password The user's password.
 * @property isVerified A flag indicating whether the user's account is verified.
 * @property discount The discount percentage associated with the user.
 * @property birthdate The user's date of birth.
 * @property salt The cryptographic salt used in password hashing.
 */
@Entity(tableName = "User")
data class User(
    @PrimaryKey(autoGenerate = true)
    val userID: Int,
    var prename: String,
    var surname: String,
    var email: String,
    var password: String,
    var isVerified: Boolean,
    var discount: Double,
    var birthdate: String,
    var salt: ByteArray
)
